CONFIG += no_fixpath
QT = core gui widgets serialport
CONFIG += no_fixpath
QT = core gui widgets serialport
CONFIG += no_fixpath
QT = core gui widgets serialport
CONFIG += no_fixpath
QT = core gui widgets serialport
CONFIG += no_fixpath
QT = core gui widgets serialport
CONFIG += no_fixpath
QT = core gui widgets serialport
CONFIG += no_fixpath
QT = core gui widgets serialport
